#-------------------------------
# General Site Settings

title: Conversatorios
logo: /assets/images/logo_a.png
author: Alejandra Gonzalez-Jimenez
description: Grupo de investigaci√≥n sobre temas cl√°sicos en el mundo moderno.
email:  desdethemyscira@gmail.com
phone: 555622-1880
address: Circuito Interior. <br> Ciudad Universitaria,<br> s/n. C.P. 04510. <br> Ciudad de M√©xico.
copyright: Copyright &copy; 2024 Designed with üñ§ by <a href = "http://alejandragj.com/" target = "_self">Alejandra Gonzalez-Jimenez</a> based on Themefisher.

menu:
- {name: Acerca de, link: '/desdethemyscira.github.io/about'}
- {name: Blog, link: '/desdethemyscira.github.io/blog'}
- {name: Memorias, link: '/desdethemyscira.github.io/portfolio'}
- {name: Eventos, link: '/desdethemyscira.github.io/eventos'}
- {name: Convocatorias, link: '/desdethemyscira.github.io/convocatorias'}
- {name: Contacto, link: '/desdethemyscira.github.io/contact'}






#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Conversatorios <br> Antig√ºedad y <br> Tradici√≥n Cl√°sicas

social:
- {icon: "ti-facebook", link: "http://www.facebook.com/desdethemyscira/"}
# - {icon: "ti-instagram", link: "#"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UCpnDuxEbJ-c-1W_HaXMjyvA"}
# - {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Los Conversatorios iniciaron como una manera de acercarnos como comunidad docente y estudiantil durante la pandemia de Covid 2019, ya que est√°bamos atravesando un a√±o muy dif√≠cil.

blurb-btn-link: '/desdethemyscira.github.io/about'
blurb-btn-name: Conoce m√°s


# About Page

# Work Process Section
work-process:
  - title : "Antolog√≠a de art√≠culos; Enfermedad y muerte. Antig√ºedad y tradici√≥n cl√°sica."
    icon : "assets/images/icons/plan.png"
    # content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title : "Tesis; La recepci√≥n de Hilas: entre las fuentes grecolatinas y la pintura de John William Watherhouse"
    icon : "assets/images/icons/design.png"
    # content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title : "Libro: La mujer √°tica en los epigramas funerarios de los siglos IV y V a. C."
    icon : "assets/images/icons/print.png"
    # content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Dra. Evelia Arteaga Conde"
    image : "assets/images/team/member-1.jpg"
    designation : " Profesora e Investigadora <br>  L√≠nea de investigaci√≥n: las mujeres y sus representaciones en Grecia antigua."
    url: "https://desdethemyscira.github.io/bio_evelia"

  - title : "Dra. Olivia Isidro V√°zquez"
    image : "assets/images/team/member-3.jpg"
    designation : "Profesora e investigadora <br> L√≠nea de investigaci√≥n: metodolog√≠a de la investigaci√≥n, neolat√≠n en Nueva Espa√±a."
    url: "https://desdethemyscira.github.io/bio_olivia"

  - title : "Dra. Martha Cecilia Jaime Gonz√°lez"
    image : "assets/images/team/member-2.jpg"
    designation: "Profesora e Investigadora <br> L√≠neas de investigaci√≥n: <br> Lengua griega y la relaci√≥n entre la literatura y las artes."
    url: "https://desdethemyscira.github.io/bio_cecilia"

  - title : "Alejandra Gonz√°lez Jim√©nez"
    image : "assets/images/team/Alegj3.jpg"
    designation : "Dise√±adora, <br> Creadora de contenido y <br> Administradora del sitio web."
    url: "https://desdethemyscira.github.io/bio_ale"

#-------------------------------
# Skills Section

# skills-title: Skills
# skills:
# - {name: Web Design, color: '#fdb157', value: '90%'}
# - {name: Logo Design, color: '#9473e6', value: '60%'}
# - {name: After Effects, color: '#bdecf6', value: '80%'}
# - {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: L√≠neas de Investigaci√≥n
experience:
- {name: Filolog√≠a cl√°sica en la interdisciplina, icon: 'icon-1.png', date: '2021', organization: 'FFyL, UNAM'}
- {name: Tradici√≥n cl√°sica como disciplina acad√©mica que estudia las relaciones entre el mundo antiguo y el moderno, icon: 'icon-2.png', date: '2021', organization: 'FFyL, Unam'}
- {name: Recepci√≥n cl√°sica; la relectura de los cl√°sicos grecolatinos a lo largo del tiempo, icon: 'icon-3.png', date: 'Present', organization: 'FFyL, UNAM'}


#-------------------------------
# Education Section

# education-title: Education
# education:
# - {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
# - {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
# - {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

#services-title: Eventos
#services:
#- {
#    name: Conversatorio 1,
#    icon: ti-palette,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }
#- {
#    name: Conversatorio 2,
#    icon: ti-vector,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: true # Add true to select section
#  }
#- {
#    name: Sesi√≥n 1,
#    icon: ti-panel,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/Conver1.jpg"
    url: "#"

  - image : "assets/images/portfolio/Conver2.jpg"
    url: "#"

  - image : "assets/images/portfolio/Conver3.jpg"
    url: "#"

  - image : "assets/images/portfolio/Conver4.jpg"
    url: "#"

  - image : "assets/images/portfolio/Conver5.jpg"
    url: "#"

  - image : "assets/images/portfolio/Conver6.jpg"
#      url: "#"


# Portfolio / Memorias Page
portfolio-label:
- {
    title : "SEMINARIOS",
    type : "seminarios"
  }
- {
    title : "CONVERSATORIOS",
    type : "conversatorios"
  }
- {
    title : "COLOQUIOS",
    type : "coloquios"
  }

portfolio-items:
  - image : "assets/images/portfolio/Conver1.jpg"
    url: "#"
    portfolio-type:
     - type: "conversatorios"
     - type: "#"

  - image : "assets/images/portfolio/Conver2.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver3.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver6.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver4.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver5.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver1.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver3.jpg"
    url: "#"
    portfolio-type:
      - type: "seminarios"
      - type: "coloquios"
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver2.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"


#-------------------------------
# Testimonials - Events Section

testimonial-items:
  - name: "La casa odiada por los dioses: la maldici√≥n representada en la Orest√≠ada de Esquilo "
    image: "assets/images/testimonial/17sesion.png"
    designation: "Decimos√©ptima sesi√≥n virtual"
    url: "https://forms.gle/Lc8eHR4giKfYDhVv6"
    #content: "Jueves 31 de agosto de 2023"
    
  - name: "Entre el sol y la muerte. Poemario y po√©tica"
    image: "assets/images/testimonial/16asesion.png"
    designation: "Decimosexta sesi√≥n virtual"
    url: "https://forms.gle/2NcWdVyyLzru8fHj7"
    #content: "Jueves 31 de agosto de 2023"

  - name: "La poes√≠a √©pica de Virgilio para CCHeros. Propuesta de secuencia did√°ctica para asignatura Lat√≠n I del Colegio de Ciencias y Humanidades de la UNAM"
    image: "assets/images/testimonial/15sesion.png"
    designation: "Decimoquinta sesi√≥n virtual"
    url: "https://forms.gle/xYUUCV6BmUoRfTmG7"
    #content: "Jueves 31 de agosto de 2023"

  - name: "Visualidad y sonoridad en la √©cfrasis de la poes√≠a tardoantigua. El ahogamiento de Leandro"
    image: "assets/images/testimonial/14sesion.png"
    designation: "Decimocuarta sesi√≥n virtual"
    url: "https://forms.gle/w1NBaNwGR1GHArXk7"
    #content: "Jueves 31 de agosto de 2023"

  - name: "IV CONVERSATORIO El espacio: representaci√≥n, concepci√≥n y relaci√≥n con el mundo grecolatino y su tradici√≥n. "
    image: "assets/images/testimonial/ivconver.png"
    designation: "IV Conversatorio virtual"
    url: "https://forms.gle/jjZyUYjcTZzU6GQk6"
    #content: "Jueves 31 de agosto de 2023"

  - name: "Propuesta did√°ctica para la ense√±anza y an√°lisis del vocabulario m√©dico en la asignatura de Griego II del Colegio de Ciencias y Humanidades"
    image: "assets/images/testimonial/13sesion.png"
    designation: "Decimotercera sesi√≥n virtual"
    url: "https://forms.gle/uw8W74HPzBAXS7wy7"
    #content: "Jueves 31 de agosto de 2023"

  - name: "Narraciones silenciosas de una tierra desconocida. Libro de cuentos"
    image: "assets/images/testimonial/12sesion.png"
    designation: "Duod√©cima sesi√≥n virtual"
    url: "https://forms.gle/2Vzt6zzRbVr2Ydpa7"
    #content: "Jueves 31 de agosto de 2023"

  - name: "In muliere virum faciat opus est: Isotta Nogarola y la virtud masculina en tres ep√≠stolas renacentistas"
    image: "assets/images/testimonial/11sesion.png"
    designation: "Und√©cima sesi√≥n virtual"
    url: "https://forms.gle/8GEtGwW8eFYfgprUA"
    #content: "Jueves 31 de agosto de 2023"

  - name: "Nos vemos en agosto"
    image: "assets/images/testimonial/jun.png"
    designation: "Nos vemos en agosto"
    #url: ""
    #content: "Mi√©rcoles 22 de febrero de 2023"

  - name: "Michel Dolores Brise√±o, La Conquista de M√©xico en De orbe novo decades de Pedro M√°rtir de Angler√≠a: edici√≥n cr√≠tica, traducci√≥n y notas."
    image: "assets/images/testimonial/10asesion.png"
    designation: "D√©cima sesi√≥n virtual"
    url: "https://forms.gle/sjcuHC7xdVDgt6ct8"
    #content: "Mi√©rcoles 22 de febrero de 2023"

  - name: "Marvin Gohan Leyva Cervantes, Medios, letras y cr√≠menes de odio hacia la comunidad LGBT+"
    image: "assets/images/testimonial/9asesion.png"
    designation: "Novena sesi√≥n virtual"
    url: "https://forms.gle/sxhcaiQx3LePyknD9"
    #content: "Mi√©rcoles 22 de febrero de 2023"

  - name: "Manuel de Jes√∫s Islas Ram√≠rez, Religi√≥n, magia y ciencia: los prolegomena del De magia universalis naturae et artis de Gaspar Schott"
    image: "assets/images/testimonial/8sesion.png"
    designation: "Octava sesi√≥n virtual"
    url: "https://forms.gle/GQK74Bsf5KE3xtC79"
    #content: "Mi√©rcoles 22 de febrero de 2023"

  - name: "Alejandra Gonz√°lez Jim√©nez, Safo en el borde: propuesta de edici√≥n cr√≠tica digital a trav√©s de LaTeX y TEI"
    image: "assets/images/testimonial/7sesion.png"
    designation: "S√©ptima sesi√≥n virtual"
    url: "https://forms.gle/xPaAcnJddKaATg9W6"
    #content: "Mi√©rcoles 22 de febrero de 2023"

  - name: "Sergio Embleton M√°rquez, Recepci√≥n del concepto de tonus en Aureliano de R√©√¥me."
    image: "assets/images/testimonial/6sesion.png"
    designation: "Sexta sesi√≥n virtual"
    url: "https://forms.gle/ZMeSB9gWR7YP6GYv5"
    #content: "Pr√≥ximamente"

  - name: "Mayra Paola Aranda Gonz√°lez, Los textos preliminares en el tratado Iuris Spiritualis Practicabilium Libri XV de don Francisco Torreblanca Villalpando."
    image: "assets/images/testimonial/5sesion.png"
    designation: "Quinta sesi√≥n virtual"
    url: "https://forms.gle/qFycdPgStY4JEEE67"
    #content: "Pr√≥ximamente"

  - name: "Emociones: Corporalidad y Corporeidad"
    image: "assets/images/testimonial/3conver2.png"
    designation: "Tercer conversatorio"
    url: "https://desdethemysciraffyl.mx/eventos"
    #content: "Pr√≥ximamente"

  - name: "Efra√≠n Ram√≠rez Carrada, El c√≠rculo como medio de unicidad con lo divino"
    image: "assets/images/testimonial/4sesion.png"
    designation: "Cuarta sesi√≥n virtual"
    url: "https://forms.gle/1ynML66d8zBto1CJ9"
    #content: "Pr√≥ximamente"

  - name: "Emociones: Corporalidad y Corporeidad"
    image: "assets/images/testimonial/3conver2.png"
    designation: "Tercer conversatorio"
    url: "https://desdethemysciraffyl.mx/eventos"
    #content: "Pr√≥ximamente"

  - name: "Santiago Campodonico, B√≠os ka√≠ Zo√©: violencia, muerte y redenci√≥n en el Orfismo"
    image: "assets/images/testimonial/3sesion.png"
    designation: "Tercera sesi√≥n virtual"
    url: "https://forms.gle/zNFmuQ6CzeJf8vqS9"
    #content: "Mi√©rcoles 35 de mayo de 2022"

  - name: "Mar√≠a de Jesus, Ars metrica de Jos√© Jim√©nez. Edici√≥n, traducci√≥n y notas"
    image: "assets/images/testimonial/2asesion.png"
    designation : "Segunda sesi√≥n virtual"
    url: "https://forms.gle/31ZFLh21RvuH6sJD9"
    #content : "Mi√©rcoles 30 de marzo de 2022"

  #- name: "Rodrigo Blum, La descripci√≥n arquitect√≥nica en la poes√≠a bizantina temprana: Paulo el Silenciario y la √âcfrasis de la Iglesia de Hagia Sof√≠a en Constantinopla"
  #  image: "assets/images/testimonial/1asesion.png"
  #  designation : "Primera sesi√≥n virtual"
  #  url: "https://forms.gle/MxCGtRSyaA4fnFmf7"
  #  content : "Mi√©rcoles 23 de febrero de 2022"

  #- name: "Santiago Campodonico, B√≠os ka√≠ Zo√©: violencia, muerte y redenci√≥n en el Orfismo"
  #  image: "assets/images/testimonial/3sesion-sw.png"
  #  designation: "Tercera sesi√≥n virtual"
  #  url: "https://forms.gle/zNFmuQ6CzeJf8vqS9"
    #content: "Mi√©rcoles 35 de mayo de 2022"

#-------------------------------
# Logos Slider Section

client-slider-items:
  - logo: "assets/images/logos/unam.png"
    url: "https://www.unam.mx/"

  - logo: "assets/images/logos/Filos.png"
    url: "http://www.filos.unam.mx/"

  - logo: "assets/images/logos/LC.png"
    url: "http://clasicas.filos.unam.mx/"

  - logo: "assets/images/logos/Filo.png"
    url: "https://www.iifilologicas.unam.mx/"

  - logo: "assets/images/logos/BNM.png"
    url: "https://bnm.iib.unam.mx/"

  - logo: "assets/images/logos/UACM.png"
    url: "https://www.uacm.edu.mx/"

  - logo: "assets/images/logos/unam.png"
    url: "https://www.unam.mx/"

  - logo: "assets/images/logos/Filos.png"
    url: "http://www.filos.unam.mx/"

  - logo: "assets/images/logos/LC.png"
    url: "http://clasicas.filos.unam.mx/"

  - logo: "assets/images/logos/Filo.png"
    url: "https://www.iifilologicas.unam.mx/"

  - logo: "assets/images/logos/BNM.png"
    url: "https://bnm.iib.unam.mx/"

  - logo: "assets/images/logos/UACM.png"
    url: "https://www.uacm.edu.mx/"

#-------------------------------
# Contact Section

contact-title: Dudas o comentarios
contact-email: desdethemyscira@gmail.com
