#-------------------------------
# General Site Settings

title: Conversatorios
logo: /assets/images/logo_a.png
author: Alejandra Gonzalez-Jimenez
description: Grupo de investigación sobre temas clásicos en el mundo moderno.
email:  desdethemyscira@gmail.com
phone: 555622-1880
address: Circuito Interior. <br> Ciudad Universitaria,<br> s/n. C.P. 04510. <br> Ciudad de México.
copyright: Copyright &copy; 2022 Designed by <a href = "http://alejandragj.com/" target = "_self">Alejandra Gonzalez-Jimenez</a> based on Themefisher.

menu:
- {name: Acerca de, link: '/desdethemyscira.github.io/about'}
- {name: Blog, link: '/desdethemyscira.github.io/blog'}
- {name: Memorias, link: '/desdethemyscira.github.io/portfolio'}
- {name: Eventos, link: '/desdethemyscira.github.io/eventos'}
- {name: Convocatorias, link: '/desdethemyscira.github.io/convocatorias'}
- {name: Contacto, link: '/desdethemyscira.github.io/contact'}






#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Conversatorios <br> Antigüedad y <br> Tradición Clásicas

social:
- {icon: "ti-facebook", link: "http://www.facebook.com/desdethemyscira/"}
# - {icon: "ti-instagram", link: "#"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UCpnDuxEbJ-c-1W_HaXMjyvA"}
# - {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Los Conversatorios iniciaron como una manera de acercarnos como comunidad docente y estudiantil durante la pandemia de Covid 2019, ya que estábamos atravesando un año muy difícil.

blurb-btn-link: '/desdethemyscira.github.io/about'
blurb-btn-name: Conoce más


# About Page

# Work Process Section
work-process:
  - title : "Antología de artículos; Enfermedad y muerte. Antigüedad y tradición clásica."
    icon : "assets/images/icons/plan.png"
    # content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title : "Tesis; La recepción de Hilas: entre las fuentes grecolatinas y la pintura de John William Watherhouse"
    icon : "assets/images/icons/design.png"
    # content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title : "Libro: La mujer ática en los epigramas funerarios de los siglos IV y V a. C."
    icon : "assets/images/icons/print.png"
    # content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Dra. Evelia Arteaga Conde"
    image : "assets/images/team/member-1.jpg"
    designation : "Coordinadora"
    url: "https://desdethemyscira.github.io/bio_evelia"

  - title : "Mtra. Olivia Isidro Vázquez"
    image : "assets/images/team/member-3.jpg"
    designation : "Coordinadora"
    url: "https://desdethemyscira.github.io/bio_olivia"

  - title : "Dra. Martha Cecilia Jaime González"
    image : "assets/images/team/member-2.jpg"
    designation : "Coordinadora"
    url: "https://desdethemyscira.github.io/bio_cecilia"

  - title : "Dra. María Leticia López Serratos"
    image : "assets/images/team/member-4.jpg"
    designation : "Coordinadora"
    url: "https://desdethemyscira.github.io/bio_leticia"

#-------------------------------
# Skills Section

# skills-title: Skills
# skills:
# - {name: Web Design, color: '#fdb157', value: '90%'}
# - {name: Logo Design, color: '#9473e6', value: '60%'}
# - {name: After Effects, color: '#bdecf6', value: '80%'}
# - {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Líneas de Investigación
experience:
- {name: Filología clásica en la interdisciplina, icon: 'icon-1.png', date: '2021', organization: 'FFyL, UNAM'}
- {name: Tradición clásica como disciplina académica que estudia las relaciones entre el mundo antiguo y el moderno, icon: 'icon-2.png', date: '2021', organization: 'FFyL, Unam'}
- {name: Recepción clásica; la relectura de los clásicos grecolatinos a lo largo del tiempo, icon: 'icon-3.png', date: 'Present', organization: 'FFyL, UNAM'}


#-------------------------------
# Education Section

# education-title: Education
# education:
# - {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
# - {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
# - {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

#services-title: Eventos
#services:
#- {
#    name: Conversatorio 1,
#    icon: ti-palette,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }
#- {
#    name: Conversatorio 2,
#    icon: ti-vector,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: true # Add true to select section
#  }
#- {
#    name: Sesión 1,
#    icon: ti-panel,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/Conver1.jpg"
    url: "#"

  - image : "assets/images/portfolio/Conver2.jpg"
    url: "#"

  - image : "assets/images/portfolio/Conver3.jpg"
    url: "#"

  - image : "assets/images/portfolio/Conver4.jpg"
    url: "#"

  - image : "assets/images/portfolio/Conver5.jpg"
    url: "#"

  - image : "assets/images/portfolio/Conver6.jpg"
#      url: "#"


# Portfolio / Memorias Page
portfolio-label:
- {
    title : "SEMINARIOS",
    type : "seminarios"
  }
- {
    title : "CONVERSATORIOS",
    type : "conversatorios"
  }
- {
    title : "COLOQUIOS",
    type : "coloquios"
  }

portfolio-items:
  - image : "assets/images/portfolio/Conver1.jpg"
    url: "#"
    portfolio-type:
     - type: "conversatorios"
     - type: "#"

  - image : "assets/images/portfolio/Conver2.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver3.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver6.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver4.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver5.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver1.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver3.jpg"
    url: "#"
    portfolio-type:
      - type: "seminarios"
      - type: "coloquios"
      - type: "conversatorios"

  - image : "assets/images/portfolio/Conver2.jpg"
    url: "#"
    portfolio-type:
      - type: "conversatorios"


#-------------------------------
# Testimonials - Events Section

testimonial-items:
  - name: "Propuesta didáctica para la enseñanza y análisis del vocabulario médico en la asignatura de Griego II del Colegio de Ciencias y Humanidades"
    image: "assets/images/testimonial/13sesion.png"
    designation: "Decimotercera sesión virtual"
    url: "https://forms.gle/uw8W74HPzBAXS7wy7"
    #content: "Jueves 31 de agosto de 2023"

  - name: "Narraciones silenciosas de una tierra desconocida. Libro de cuentos"
    image: "assets/images/testimonial/12sesion.png"
    designation: "Duodécima sesión virtual"
    url: "https://forms.gle/2Vzt6zzRbVr2Ydpa7"
    #content: "Jueves 31 de agosto de 2023"

  - name: "In muliere virum faciat opus est: Isotta Nogarola y la virtud masculina en tres epístolas renacentistas"
    image: "assets/images/testimonial/11sesion.png"
    designation: "Undécima sesión virtual"
    url: "https://forms.gle/8GEtGwW8eFYfgprUA"
    #content: "Jueves 31 de agosto de 2023"

  - name: "Nos vemos en agosto"
    image: "assets/images/testimonial/jun.png"
    designation: "Nos vemos en agosto"
    #url: ""
    #content: "Miércoles 22 de febrero de 2023"

  - name: "Michel Dolores Briseño, La Conquista de México en De orbe novo decades de Pedro Mártir de Anglería: edición crítica, traducción y notas."
    image: "assets/images/testimonial/10asesion.png"
    designation: "Décima sesión virtual"
    url: "https://forms.gle/sjcuHC7xdVDgt6ct8"
    #content: "Miércoles 22 de febrero de 2023"

  - name: "Marvin Gohan Leyva Cervantes, Medios, letras y crímenes de odio hacia la comunidad LGBT+"
    image: "assets/images/testimonial/9asesion.png"
    designation: "Novena sesión virtual"
    url: "https://forms.gle/sxhcaiQx3LePyknD9"
    #content: "Miércoles 22 de febrero de 2023"

  - name: "Manuel de Jesús Islas Ramírez, Religión, magia y ciencia: los prolegomena del De magia universalis naturae et artis de Gaspar Schott"
    image: "assets/images/testimonial/8sesion.png"
    designation: "Octava sesión virtual"
    url: "https://forms.gle/GQK74Bsf5KE3xtC79"
    #content: "Miércoles 22 de febrero de 2023"

  - name: "Alejandra González Jiménez, Safo en el borde: propuesta de edición crítica digital a través de LaTeX y TEI"
    image: "assets/images/testimonial/7sesion.png"
    designation: "Séptima sesión virtual"
    url: "https://forms.gle/xPaAcnJddKaATg9W6"
    #content: "Miércoles 22 de febrero de 2023"

  - name: "Sergio Embleton Márquez, Recepción del concepto de tonus en Aureliano de Réôme."
    image: "assets/images/testimonial/6sesion.png"
    designation: "Sexta sesión virtual"
    url: "https://forms.gle/ZMeSB9gWR7YP6GYv5"
    #content: "Próximamente"

  - name: "Mayra Paola Aranda González, Los textos preliminares en el tratado Iuris Spiritualis Practicabilium Libri XV de don Francisco Torreblanca Villalpando."
    image: "assets/images/testimonial/5sesion.png"
    designation: "Quinta sesión virtual"
    url: "https://forms.gle/qFycdPgStY4JEEE67"
    #content: "Próximamente"

  - name: "Emociones: Corporalidad y Corporeidad"
    image: "assets/images/testimonial/3conver2.png"
    designation: "Tercer conversatorio"
    url: "https://desdethemysciraffyl.mx/eventos"
    #content: "Próximamente"

  - name: "Efraín Ramírez Carrada, El círculo como medio de unicidad con lo divino"
    image: "assets/images/testimonial/4sesion.png"
    designation: "Cuarta sesión virtual"
    url: "https://forms.gle/1ynML66d8zBto1CJ9"
    #content: "Próximamente"

  - name: "Emociones: Corporalidad y Corporeidad"
    image: "assets/images/testimonial/3conver2.png"
    designation: "Tercer conversatorio"
    url: "https://desdethemysciraffyl.mx/eventos"
    #content: "Próximamente"

  - name: "Santiago Campodonico, Bíos kaí Zoé: violencia, muerte y redención en el Orfismo"
    image: "assets/images/testimonial/3sesion.png"
    designation: "Tercera sesión virtual"
    url: "https://forms.gle/zNFmuQ6CzeJf8vqS9"
    #content: "Miércoles 35 de mayo de 2022"

  - name: "María de Jesus, Ars metrica de José Jiménez. Edición, traducción y notas"
    image: "assets/images/testimonial/2asesion.png"
    designation : "Segunda sesión virtual"
    url: "https://forms.gle/31ZFLh21RvuH6sJD9"
    #content : "Miércoles 30 de marzo de 2022"

  #- name: "Rodrigo Blum, La descripción arquitectónica en la poesía bizantina temprana: Paulo el Silenciario y la Écfrasis de la Iglesia de Hagia Sofía en Constantinopla"
  #  image: "assets/images/testimonial/1asesion.png"
  #  designation : "Primera sesión virtual"
  #  url: "https://forms.gle/MxCGtRSyaA4fnFmf7"
  #  content : "Miércoles 23 de febrero de 2022"

  #- name: "Santiago Campodonico, Bíos kaí Zoé: violencia, muerte y redención en el Orfismo"
  #  image: "assets/images/testimonial/3sesion-sw.png"
  #  designation: "Tercera sesión virtual"
  #  url: "https://forms.gle/zNFmuQ6CzeJf8vqS9"
    #content: "Miércoles 35 de mayo de 2022"

#-------------------------------
# Logos Slider Section

client-slider-items:
  - logo: "assets/images/logos/unam.png"
    url: "https://www.unam.mx/"

  - logo: "assets/images/logos/Filos.png"
    url: "http://www.filos.unam.mx/"

  - logo: "assets/images/logos/LC.png"
    url: "http://clasicas.filos.unam.mx/"

  - logo: "assets/images/logos/Filo.png"
    url: "https://www.iifilologicas.unam.mx/"

  - logo: "assets/images/logos/BNM.png"
    url: "https://bnm.iib.unam.mx/"

  - logo: "assets/images/logos/UACM.png"
    url: "https://www.uacm.edu.mx/"

  - logo: "assets/images/logos/unam.png"
    url: "https://www.unam.mx/"

  - logo: "assets/images/logos/Filos.png"
    url: "http://www.filos.unam.mx/"

  - logo: "assets/images/logos/LC.png"
    url: "http://clasicas.filos.unam.mx/"

  - logo: "assets/images/logos/Filo.png"
    url: "https://www.iifilologicas.unam.mx/"

  - logo: "assets/images/logos/BNM.png"
    url: "https://bnm.iib.unam.mx/"

  - logo: "assets/images/logos/UACM.png"
    url: "https://www.uacm.edu.mx/"

#-------------------------------
# Contact Section

contact-title: Dudas o comentarios
contact-email: desdethemyscira@gmail.com
